easy_admin:
    entities:
        Question:
            class: App\Entity\Question
            form:
                fields:
                    - name
                    - category
                    - level
                    - answerUidType
                    - questionType
                    -
                      property: answers
                      type: collection
                      type_options:
                          entry_type: App\Form\AnswersEmbeddedForm
                          allow_delete: true
                          allow_add: true
                          by_reference: false
            list:
                title: Questions
                help: List of questions to compile test session template
                actions: ['show']
                fields:
                    - id
                    - name
                    - category
                    - level
            search:
                fields: ['id', 'name']

        Answer:
            class: App\Entity\Answer
            form:
                fields:
                    - { property: 'answer', type: 'text_editor' }
                    - isValid
                    - question
        Category:
            class: App\Entity\Category
            form:
                fields:
                    - name
        TestSessionTemplate:
            class: App\Entity\TestSessionTemplate
            list:
                actions:
                    -
                      name: 'exam_generate'
                      type: 'route'
            form:
                fields:
                    - name
                    - timeLimit
                    - cutoffSuccess
                    -
                      property: items
                      type: collection
                      type_options:
                          entry_type: App\Form\TestSessionItemsEmbeddedForm
                          allow_delete: true
                          allow_add: true
                          by_reference: false


        TestSession:
            class: App\Entity\TestSession

        TestSessionItem:
            class: App\Entity\TestSessionItem
