easy_admin:
    design:
        menu:
            - { entity: 'Question', label: 'Questions' }
            - { entity: 'TestSessionTemplate', label: 'Test Session Template' }
            - { entity: 'TestSession', label: 'Test Sessions' }
            - { entity: 'Category', label: 'Categories' }
        form_theme:
            - '@EasyAdmin/form/bootstrap_4.html.twig'
        assets:
            js:
                - '/bundles/easyadmin/form-type-text-editor.js'
            css:
                - '/bundles/easyadmin/form-type-text-editor.css'
    entities:
        Question:
            class: App\Entity\Question
            form:
                fields:
                    -
                      property: name
                      type: 'text'
                    - category
                    -
                      property: level
                      type: 'choice'
                      help: 'Complexity level from 1 to 6'
                      type_options:
                          mapped: true
                          expanded: false
                          multiple: false
                          choices: { 1: '1', 2: '2', 3: '3', 4: '4', 5: '5', 6: '6' }
                    -
                      property: answerUidType
                      type: 'choice'
                      help: 'Number or Alphabet list (1,2,3 vs A,B,C)'
                      type_options:
                          mapped: true
                          expanded: false
                          multiple: false
                          choices: { 'Alphabetical': 'alpha', 'Numerical': 'num' }
                    -
                      property: questionType
                      type: 'choice'
                      help: 'Checkboxes or Radio buttons'
                      type_options:
                          mapped: true
                          expanded: false
                          multiple: false
                          choices: { 'Checkboxes': 'checkboxes', 'Radio': 'radio' }
                    - { type: 'section', label: 'Answers'}
                    -
                      property: answers
                      type: collection
                      type_options:
                          entry_type: App\Form\AnswersEmbeddedForm
                          allow_delete: true
                          allow_add: true
                          by_reference: false
            list:
                title: Questions
                help: List of questions to compile test session template
                actions: ['show']
                fields:
                    - id
                    - name
                    - category
                    - level
            search:
                fields: ['id', 'name']

        TestSessionTemplate:
            class: App\Entity\TestSessionTemplate
            list:
                title: 'Test Session templates'
                actions:
                    -
                      name: 'admin_exam_generate'
                      label: 'Generate Test Session'
                      type: 'route'
            form:
                title: 'Create Test session template'
                fields:
                    - name
                    -
                      property: timeLimit
                      type: 'integer'
                      help: 'Time limit per Test Session in minutes'
                    -
                      property: cutoffSuccess
                      type: 'integer'
                      help: 'Percent value to pass exam (from 1 to 100)'
                    -
                      property: items
                      type: collection
                      type_options:
                          entry_type: App\Form\TestSessionItemsEmbeddedForm
                          allow_delete: true
                          allow_add: true
                          by_reference: false

        TestSession:
            class: App\Entity\TestSession
            list:
                fields:
                    - id
                    - email
                    - testSessionTemplate
                    - startedAt
                    - finishedAt
                    - result
                    - { property: 'test_session_url', type: 'url' }
                actions: ['show', '-new']

        Category:
            class: App\Entity\Category
            form:
                fields:
                    - name
